services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: laravel12_app

    working_dir: /var/www/html

    volumes:
      - ./:/var/www/html

    ports:
      - "8000:8000"

    depends_on:
      - mysql

    networks:
      - laravel

  nginx:
    image: nginx:latest

    container_name: laravel12_nginx

    ports:
      - "8080:80"

    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

    networks:
      - laravel

  mysql:
    image: mysql:8.4

    container_name: laravel12_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: footwear_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123456

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel: