services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: laravel12_app

    working_dir: /var/www/html

    volumes:
      - ./:/var/www/html

    ports:
      - "8000:8000"

    depends_on:
      - mysql

    networks:
      - laravel

  mysql:
    image: mysql:8.4

    container_name: laravel12_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel: